language: cpp
compiler: clang
os: windows
python: 3.8
install:
  - vcpkg install curl
  - vcpkg install cryptopp
script:
  - cmake --configure .
  - cmake --build . --config Release
  - ctest --output-on-failure
