language: cpp
compiler: clang
os: windows
arch: amd64

python: 3.8

before_install:
  - git clone https://github.com/Microsoft/vcpkg.git
  - cd vcpkg
  - powershell ./bootstrap-vcpkg.sh
  - powershell ./vcpkg integrate install
  - powershell ./vcpkg update
  - powershell ./vcpkg install curl
  - powershell ./vcpkg install cryptopp
script:
  - cmake --configure .
  - cmake --build . --config Release
  - ctest --output-on-failure
